# The URL the site will be built for
base_url = "https://ba11b0y.github.io/rahul/"
theme = "lekhz"


# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true


[extra]
# Put all your custom variables here
lekhz_name = "Rahul"
lekhz_about = """Hello, I'm Rahul. Here are some things I feel you'll like to know about me! 
- My most recent interest is in AI alignment and safety!
- I am a MS student at Virginia Tech and enjoy learning about OS, compilers, and programming languages.
- Apart from computers, I enjoy everything outdoors and enjoy a lot of sports.
"""
lekhz_email = "jprrahultiwari@gmail.com"
lekhz_post_limit = 3
lekhz_goatcounter_code = "https://rtiwari.goatcounter.com/count"
# Example profiles configuration
lekhz_profiles = [
    { name = "GitHub", url = "https://github.com/ba11b0y" },
    { name = "LinkedIn", url = "https://www.linkedin.com/in/ba11b0y/" },
]
